#!/bin/bash

echo ================ File $1 ================
echo
cat $1
echo
echo ================ File $1 ================

echo [+] Compiling $1
g++ $1 -o $(echo $1 | cut -d "." -f 1)

if [ $? -eq 0 ]; then
echo [+] Compiling Successful
fi

echo [+] Running Program
echo

./$(echo $1 | cut -d "." -f 1)
